export const Lang = {
  CLOSE: `close`,
  ORIGINAL_TITLE: `Original`,
  DIRECTOR: `Director`,
  WRITERS: `Writers`,
  ACTORS: `Actors`,
  RELEASE_DATE: `Release Date`,
  RUNTIME: `Runtime`,
  COUNTRY: `Country`,
  GENRE: `Genre`,
  GENRES: `Genres`,
  ALL_MOVIES: `All movies`,
  WATCHLIST: `Watchlist`,
  HISTORY: `History`,
  FAVORITES: `Favorites`,
  ADD_TO_WATCHLIST: `Add to watchlist`,
  ALREADY_WATCHED: `Already watched`,
  ADD_TO_FAVORITES: `Add to favorites`,
  DELETE: `Delete`,
  DELETING: `Deleting...`,
  COMMENTS: `Comments`,
  COMMENT_INPUT_PLACEHOLDER: `Select reaction below and write comment here`,
  EMPTY_LIST_MESSAGE: `There are no movies in our database`,
  SHOW_MORE: `Show more`,
  STATS: `Stats`,
  SORT_BY: `Sort by`,
  DEFAULT: `default`,
  DATE: `date`,
  RATING: `rating`,
  FILMS_STATS_MESSAGE: `movies inside`,
  ALL_MOVIES_TITLE: `All movies. Upcoming`,
  LOADING: `Loading...`,
  YOUR_RANK: `Your rank`,
  RANK_SCI_FIGHTER: `Sci-Fighter`,
  SHOW_STATS: `Show stats`,
  YOU_WATCHED: `You watched`,
  TOTAL_DURATION: `Total duration`,
  TOP_GENRE: `Top genre`,
  MOVIES: `movies`,
  HOURS_SHORT: `h`,
  MINUTES_SHORT: `m`,
  ALL_TIME: `All time`,
  TODAY: `Today`,
  WEEK: `Week`,
  MONTH: `Month`,
  YEAR: `Year`,
};
