export const LANG = {
  CLOSE: `close`,
  ORIGINAL_TITLE: `Original`,
  DIRECTOR: `Director`,
  WRITERS: `Writers`,
  ACTORS: `Actors`,
  RELEASE_DATE: `Release Date`,
  RUNTIME: `Runtime`,
  COUNTRY: `Country`,
  GENRES: `Genres`,
  ADD: `Add`,
  TO: `to`,
  IN: `in`,
  ALL_MOVIES: `All movies`,
  WATCHLIST_CAP: `Watchlist`,
  WATCHLIST: `watchlist`,
  ALREADY: `Already`,
  WATCHED: `watched`,
  HISTORY_CAP: `History`,
  FAVORITES: `favorites`,
  FAVORITES_CAP: `Favorites`,
  DELETE: `Delete`,
  DELETING: `Deleting...`,
  COMMENTS: `Comments`,
  COMMENT_INPUT_PLACEHOLDER: `Select reaction below and write comment here`,
  EMPTY_LIST_MESSAGE: `There are no movies in our database`,
  MARK: `Mark`,
  AS: `as`,
  SHOW_MORE: `Show more`,
  STATS: `Stats`,
  SORT_BY: `Sort by`,
  DEFAULT: `default`,
  DATE: `date`,
  RATING: `rating`,
  FILMS_STATS_MESSAGE: `movies inside`,
  ALL_MOVIES_TITLE: `All movies. Upcoming`,
  TOP_RATED_TITLE: `Top rated`,
  MOST_COMMENTED: `Most commented`,
  LOADING: `Loading...`,
  YOUR_RANK: `Your rank`,
  RANK_SCI_FIGHTER: `Sci-Fighter`,
  SHOW_STATS: `Show stats`,
  YOU_WATCHED: `You watched`,
  TOTAL_DURATION: `Total duration`,
  TOP_GENRE: `Top genre`,
  MOVIES: `movies`,
  HOURS_SHORT: `h`,
  MINUTES_SHORT: `m`
};
